### PR TITLE
use PREFIX env var here

### LINKED ISSUE #4: xxx does not build with recent versions of areaDetector
There are issues with building xxx with areaDetector.  areaDetector has optional dependencies on external libraries (HDF5, OPENCV, EPICS-V4, etc.) that are not correctly captured by the synApps/support/configure synApps/support/CONFIG_SITE, and xxx/configure/RELEASE and xxx/xxxApp/src/Makefile.  

I have modified the dxp/configure/RELEASE and quadEM/configure/RELEASE so they optionally include the areaDetector/configure/RELEASE_PATHS.local and RELEASE_PRODS.local so they will properly build with the configuration defined in areaDetector/configure.  Something similar needs to be done for xxx.

### LINKED ISSUE #28: st.cmd.* has hard coded IOC name
When using the XXX module as an IOC template, it is easy to change the IOC prefix in one place: `common.iocsh`.  However, the `st.cmd.*` files use a hard-coded `IOC=xxx` definition.

This should use `IOC=$(PREFIX)` instead.

### PR DESCRIPTION
**Pull request by prjemian**
fixes #28

### CODE REVIEW

**Comment by prjemian** [comment]
*This* module expects `$IOC` to **not** have a trailing colon `:`.  The `$PREFIX` must be edited or PVs with `::` will be produced.

Here's a way to do this in bash: [SO post](https://stackoverflow.com/a/27658733/1046449) 

This does not work in the IOC shell:

```
iocxxx> echo $(PREFIX)
bc2:
iocxxx> echo $(PREFIX::-1)
macLib: macro PREFIX::-1 is undefined (expanding string echo $(PREFIX::-1))
```

so do not merge this PR until a solution is found.

**Comment by prjemian** [comment]
@keenanlang @anjohnson : How to delete the last character from an EPICS environment variable in the IOC console?

**Comment by prjemian** [comment]
Going to tech-talk with this question.

**Comment by prjemian** [comment]
Looking at the EPICS [AppDevGuide](https://epics.anl.gov/base/R3-14/12-docs/AppDevGuide/node19.html#SECTION001921000000000000000), I'm not sure this is possible unless using some other tool, such as lua.  The IOC's `help` command shows this for lua: `luaSpawn        luash`

@keenanlang can you construct the lua command to do this( possibly defining a new env var if needed)?

**Comment by prjemian** [comment]
luash help: https://github.com/epics-modules/lua/blob/master/documentation/using_lua_shell.md

**Comment by prjemian** [comment]
@keenanlang : in lua, something like  PREFIX:sub(?, ?) but how to do that?

**Comment by keenanlang** [comment]
I wouldn't suggest doing this with lua, but it can be done. In the latest release of the lua module, you can do:

    PREFIX = os.getenv("PREFIX")
    epicsEnvSet("SOME_NAME", string.sub(PREFIX, 1, #PREFIX - 1)

The only difference for older versions is you'll have to put iocsh.epicsEnvSet

Put that in a file and call it with luash, there is no current equivalent to iocshRun to do one-liners.

I'd instead take Michael's suggestion from tech-talk and define a macro that's just xxx and use that to construct PREFIX. At least for the time being. There has been discussion of this issue already on iocStats to change the databases so that you can get rid of the trailing separator, then there would be no need to have two macros. See:

https://github.com/epics-modules/iocStats/pull/32
https://github.com/epics-modules/iocStats/issues/31

**Comment by prjemian** [comment]
A change in iocStats's databases is the best way.  The others are more fragile.  It would be interesting to demonstrate this with lua.  Can you construct the steps to run that in the IOC shell?  Treat me like the lua novice that I am.

**Comment by keenanlang** [comment]
To do it with lua, just take those two lines and put them into a file, let's say 'substring.lua'.

If you put that file in the IOC's startup directory, the IOC doesn't need to be told anything else. If you want to put it in a subdirectory, then you'll want to define the environment variable LUA_SCRIPT_PATH. I generally put all the lua stuff in a scripts subdirectory so I have a line in the ioc startup script like so:

    epicsEnvSet("LUA_SCRIPT_PATH","./scripts")

Then, later in the startup script, when you want the lua commands to be run, just do:

    luash "substring.lua"

**Comment by prjemian** [comment]
Closing since this work is superceded by #31.

**Pull request closed without merging**
